- client/client.go
- cmd/rport/main.go
- cmd/rportd/main.go
- server/client_session.go
- server/handler.go
- server/server.go
DEV-1178
- Update env variables naming
- Improve --help output and add examples
- Fix handling --authfile restrictions
- Do not exit client on authentication errors
> Improve server and client usage in various scenarios

- .circleci/config.yml
- .circleci/publish-packages.sh
- .circleci/unpublish-packages.sh
- .goreleaser.yml
- Makefile
- README.md
> Add CircleCI config and it's dependencies

- cmd/rportd/main.go
- server/api_listener.go
- server/server.go
> Add option to serve static files when running API server

- README.md
- api-doc.yml
- client/client.go
- server/api.go
- server/api_listener.go
- server/client_listener.go
- share/user.go
- share/users.go
Part of DEV-1650
Similar to #16 (canceled) but with changes on a client side too (client.go)
> Drop support for address filtering in authfile JSON

- api-doc.yml
- server/api.go
- server/api_listener.go
- server/client_listener.go
- server/client_session.go
- server/server.go
- server/session_repository.go
- server/session_service.go
This will allow to reuse more code between api_listener and client_listener
> Refactoring:  add new layer of abstraction on top of ClientSessionRepo

- api-doc.yml
- cmd/rportd/main.go
- server/api.go
- server/api_listener.go
- server/client_listener.go
- server/server.go
- server/session_service.go
> Show fingerprint and connect URL on API /status response object. New CLI arg allows to specify custom URL

- server/api_listener.go
Now API will return InternalServerError instead of failing quietly
> Add handler for panicking HTTP handlers

- server/api.go
- server/client_session.go
- server/session_service.go
- server/tunnel.go
- server/tunnel_acl.go
> Add option to specify tunnel ACL (range of allowed IPs)

- api-doc.yml
- server/api.go
This PR adds a container object for API responses that should become paginated.
Also updated swagger doc with recently added but forgotten-to-document values on /sessions
Please keep an extra eye on my swagger changes, I am not too familiar with this format.
DEV-1637
> API: Add pagination boilerplate

- api-doc.yml
- cmd/rportd/main.go
- rportd.example.conf
- server/api_listener.go
- server/config.go
- server/server.go
- share/http_server.go
- share/http_server_test.go
Add `cert_file` and `key_file` config options for api with https.
> DEV-1707: Add https cert and key config options

- client/config.go
- cmd/rport/main.go
- cmd/rportd/main.go
- rport.example.conf
- rportd.example.conf
- server/config.go
- share/root.go
Prevent rport(d) running as root unless allow root is set.
> DEV-1711: Prevent rport(d) running as root.

- README.md
- api-doc.yml
- cmd/rport/main.go
- cmd/rportd/main.go
- docs/client-auth.md
- rport.example.conf
- rportd.example.conf
- server/api.go
- server/api_test.go
- server/client_listener.go
- server/config.go
- renaming: username -> client auth id;
- update examples with using new client auth credentials;
- do not check whether run cmd is allowed since it became always allowed;
> DEV-1988: Imrpovements for Release Prepaartion

- api-doc.yml
- cmd/rportd/main.go
- rport.example.conf
- rportd.example.conf
- server/api.go
- server/cgroups/group.go
- server/client_service.go
- fix config files;
- API GET `/client-groups`: populate group with disconnected clients as well;
> DEV-1988: Release preparation fixes

- api-doc.yml
- server/cgroups/sqlite.go
- server/clients/sort.go
- server/clients/sort_test.go
- API get clients and groups: sort ignoring case;
- fix api doc.
> DEV-1988: Release Preparation Improvements

- api-doc.yml
- server/api.go
- Add PUT /me to update profile info
- rename DELETE /login to /logout
- improved swagger API docs
> DEV-2167: Add PUT /me to update profile info, API docs improved

- cmd/rportd/main.go
- go.sum
- rportd.example.conf
- server/api.go
- server/client_service.go
- server/client_service_test.go
- server/config.go
- server/config_test.go
- server/ports/port_distributor.go
- server/server.go
- add to settings 'used ports' to describe what ports can be used;
- check local port if it's among allowed ports
> DEV-2212: Whitlelist of allowed ports to use

- api-doc.yml
- client/monitoring/processes/processes.go
- server/api.go
api /status should show "tunnel_proxy_enabled" true/false
also fixed correct handling of "pm_enabled"
> Dev 2430 reverse proxy status

- .github/workflows/deploy.yml
switching to go 1.17 to use go:embed
> DEV-2454 go 1.17 in GitHub workflow deploy.yml

- cmd/rportd/main.go
- rportd.example.conf
- server/client_service.go
- server/clients/cleanup_test.go
- server/clients/client.go
- server/clients/data_test.go
- server/clients/init_test.go
- server/clients/sqlite.go
- server/clients/sqlite_test.go
- server/config.go
- server/server.go
When `cleanup_clients = false`, keep clients forever.
> DEV-2475: Add option to keep clients forever

- .github/workflows/lint.yml
- .golangci.yml
- Makefile
- server/client_service.go
- server/clients/clienttunnel/tunnel_allowed.go
- Fix request type for client checks of tunnel allowed
- Ignore `unknown request` errors for backwards compatibility
> [DEV-2491] Fix client checks and compatibility

- server/api_handler_clients.go
- server/client_service.go
- server/client_service_test.go
- server/clients/client.go
- server/clients/clienttunnel/tunnel.go
- server/clients/clienttunnel/tunnel_tcp.go
- server/clients/clienttunnel/tunnel_udp.go
- server/clients/clienttunnel/tunnel_udp_test.go
- server/ports/port_distributor.go
- share/models/remote.go
https://tracker.cloudradar.info/issue/DEV-2572/Combined-udp-tcp-tunnels
> [DEV-2572] Allow tcp and udp tunnels on the same port

- server/clients/client.go
- server/clients/clienttunnel/tunnel_tcp.go
> Re-order some structs to ensure int64 is declared first

- api-doc/openapi/components/schemas/JobPartial.yaml
- api-doc/openapi/paths/ws_commands.yaml
- api-doc/openapi/paths/ws_scripts.yaml
- client/command.go
- client/command_test.go
- server/client_listener.go
- server/client_listener_test.go
- server/clients/client.go
- server/clients/clienttunnel/tunnel_tcp.go
- share/models/job.go
- share/test/ssh.go
- share/ws/websocket.go
- share/ws/websocket_test.go
Stream stdout and stderr output from clients to the websocket
> [DEV-2592] Implement output streaming to websocket

- .golangci.yml
- cmd/rportd/main.go
- plus/config.go
- plus/license/config.go
- plus/loader/loader.go
- plus/manager.go
- plus/manager_test.go
- rportd.example.conf
- server/api_handler_plus_test.go
- server/api_login_auth_provider_test.go
- server/config.go
- server/config_load_test.go
- server/plus.go
- server/plus_test.go
- server/server.go
https://tracker.rport.io/issue/DEV-2668/Unlocking-plus-by-licence-key
> [DEV-2668] Unlocking-plus-by-licence-key

- server/api_router.go
https://tracker.rport.io/issue/DEV-2702/Broken-password-change
> secureAPI. instead of api. to enable put method

- client/client.go
- client/command.go
- client/command_test.go
- client/system/encoding.go
- client/system/encoding_nix.go
- client/system/encoding_test.go
- client/system/encoding_win.go
- client/system/script.go
https://tracker.rport.io/issue/DEV-2687/broken-support-for-special-characters-on-windows
> [DEV-2687] Use encoding for writing script file when available

- server/api_handler_users.go
this would have caused a bug in updating a user pwd
> check for nil pointer

- server/api/authorization/model.go
- server/api_handler_login_test.go
> Extract prefixedpwd avoid strings.Index

- rportd.example.conf
- server/api_handler_clients.go
- server/api_handler_clients_test.go
- server/caddy/config.go
- server/caddy/config_test.go
- share/models/remote.go
https://tracker.rport.io/issue/DEV-2757/missing-port-on-tunnel-URL
> [DEV-2757] Missing port on tunnel URL

- plus/capabilities/license/license.go
- plus/license/config.go
- plus/manager.go
- server/api_handler_clients.go
- server/api_handler_commands.go
- server/api_handler_commands_test.go
- server/api_handler_users.go
- server/api_helper_commands.go
- server/api_helper_jobs.go
- server/clients/client.go
- server/clients/client_service.go
- server/plus.go
- server/plus_test.go
- server/server.go
https://tracker.rport.io/issue/DEV-2707/Limit-max-rport-clients-and-users-on-rport-plus
> [DEV-2707] Limit max rport clients and users on rport plus

- server/api_handler_commands_test.go
- server/api_helper_clients.go
- server/api_helper_commands.go
- server/api_helper_jobs.go
- server/clients/client_service.go
https://tracker.rport.io/issue/DEV-2696/return-disconnect-error-on-script-command-execution
> [DEV-2696] Return error for disconnected clients when executing

- .github/workflows/lint.yml
- api-doc/openapi/openapi.yaml
- api-doc/openapi/paths/clients_{client_id}_tunnels_{tunnel_id}_acl.yaml
- server/api_handler_clients.go
- server/api_handler_clients_test.go
- server/api_handler_users.go
- server/api_router.go
- server/clients/client_service.go
- server/clients/clienttunnel/tunnel.go
- server/clients/clienttunnel/tunnel_internal_proxy.go
- server/clients/clienttunnel/tunnel_tcp.go
- server/clients/clienttunnel/tunnel_udp.go
- server/clients/clienttunnel/tunnel_udp_test.go
https://tracker.rport.io/issue/DEV-2566/Update-the-ACL-of-a-running-tunnel
> [DEV-2566] Update client tunnel acl endpoint

- api-doc/openapi/paths/client-groups.yaml
- api-doc/openapi/paths/client-groups_{group_id}.yaml
- server/api_handler_clientgroups.go
- server/cgroups/group.go
- server/cgroups/sqlite.go
https://tracker.rport.io/issue/DEV-2772/client-group-filters
> [DEV-2772] Fields and filters query options for client groups

- api-doc/openapi/components/schemas/ClientTag.yaml
- api-doc/openapi/openapi.yaml
- api-doc/openapi/paths/client-tags.yaml
- server/api_handler_clienttags.go
- server/api_router.go
https://tracker.rport.io/issue/DEV-2807/client-tags-missing
> [DEV-2807] Client tags endpoint

- server/clients/clienttunnel/guac/index.html
- server/clients/clienttunnel/guac_token.go
- server/clients/clienttunnel/tunnel_proxy_connector_rdp.go
https://tracker.rport.io/issue/DEV-2777/
> Issue/dev 2777/add sound to web rdp

- client/client.go
This fixes an issue where the connection was breaking, so there was another round of the connection loop. However the connection was still marked as "active", so the SSH request handling go-routine wasn't restarted. The fix just marks the connection as no longer active on a connection break.
Also, the PR includes some additional debug logs. Particularly, the request types and payloads received from the server are now logged. This should give some clues as to what request a client might be processing at the time of client issues.
> [DEV-2836] Partially unresponsive clients after server restart

- cmd/rportd/usercli/password_test.go
- cmd/rportd/usercli/usercli_test.go
- docs/content/get-started/no02-api-auth.md
- docs/content/get-started/no15-messaging.md
- go.mod
- rportd.example.conf
- server/acme/acme_test.go
- server/api/message/url.go
- server/api/message/url_test.go
- server/api_listener.go
- server/chconfig/config.go
- server/chconfig/config_test.go
- server/clients/clienttunnel/tunnel_internal_proxy_test.go
https://tracker.rport.io/issue/DEV-2821/built-in-2FA-email-sending
> [DEV-2821] Add url delivery method for 2fa tokens

- server/chconfig/config.go
- server/chconfig/config_test.go
https://tracker.rport.io/issue/DEV-2842/Allow-CORS
> Cors config validation

- Makefile
- go.mod
- go.sum
- plus/license/config.go
- server/plus.go
- server/scheduler/scheduler.go
https://tracker.rport.io/issue/DEV-2919/Arm-Rport-Plus-licence
> [DEV-2919] Arm Rport Plus Licence

- .github/workflows/deploy.yml
https://tracker.rport.io/issue/DEV-3118/Ensure-rport-plus.so-installed-on-demo-node1-server
> [DEV 3118] Ensure rport plus deployed on demo server
