realvnc-labs/rport

.goreleaser.yml
Makefile

Now 'build' builds minimalistic version and 'build-debug' builds version with debug symbols and race detection, allowing to run delve session

Update Makefile build scripts to allow building debug-version

---

api-doc.yml
cmd/rportd/main.go
go.mod
go.sum
server/api.go
server/api_listener.go
server/api_session.go
server/bearer_auth.go
server/client_listener.go
server/server.go
server/session_repository.go

DEV-1611
- API documentation added (swagger 2.0), see file api-doc.yml
- new CLI options --api-auth and --api-jwt-secret
- allow HTTP-basic authorization
- allow Bearer authorization using JWT tokens
- information about token expiration stored in-memory, meaning server restart will shutdown active api user sessions.  Later we will add support for persistent storage. For this purpose public methods of storage managers (APISessionStorage and ClientSessionStorage) were unified.
- initial token expiration still can be specified in /login requests with token-lifetime option. Max value is 90 days (in seconds). Default: 10 min.
- each request with `Authorization: Bearer XXX` header increases token lifetime (+10 min). Token does not hold expiration date meaning it remains unchanged.

Add authorization checks for API and API documentation

---

.circleci/config.yml
.golangci.yml

Now `make docker-golangci-lint` executes really quick when running locally because all the dependencies already in-place.
CI job duration also shortened from ~45 sec to ~8sec

Update golangci linter config to honor gomod-vendored dependencies

---

README.md
cmd/rport/main.go
cmd/rportd/main.go

Addressing a few issues from DEV-1589:
- -l and -p options were merged into --addr (-a) option.
- help updated with IPv6 addresses usage
- typos fixed in README

Rework CLI args naming

---

client/client.go
cmd/rport/main.go
cmd/rportd/main.go
server/api.go
server/api_listener.go
server/client_listener.go
server/server.go
server/tunnel.go
share/conn_ws.go
share/logger.go
share/users.go

DEV-1634
I've also renamed the `Logger.Errorf` function to `FormatError`. New `Errorf` function now prints a message to a log, similarly to `logrus.Logger` interface we have in cagent and frontman.

Allow logging to a file and specifying log verbosity (error, info, debug)

---

go.mod
go.sum

Looks like it wasn't updated properly after installing gopsutil previosly

Fix dependencies list with `go mod tidy`

---

api-doc.yml
client/client.go
cmd/rport/main.go
cmd/rportd/main.go
go.mod
go.sum
server/api.go
server/client_listener.go
server/client_session.go
server/ports/port_distributor.go
server/server.go
server/session_service.go
share/remote.go
share/sets.go

New CLI option --exclude-ports added to allow server administrators to specify ports forbidden to use
DEV-1650

Implement random server port assignment when the 'local' part is not specified (either on CLI or API request)

---

client/client.go
client/client_test.go
cmd/rport/main.go
server/client_listener.go
server/session_service.go
share/protocol.go

- Simplify Client type. Now it does not hold Config inside
- Most of chshare.Config fields now initialized only once on Client startup
- chshare.Config renamed to chshare.ConnectionRequest. It's more precise name and also eliminates confusion with chserver.Config/chclient.Config
Part of DEV-1633 (config file implementation)

Refactoring of client configuration options

---

client/config.go
client/config_test.go

Set default user agent to rport {version}, but allow user to override it with headers option.

DEV-1759: Set default user agent to rport {version}

---

client/client.go
client/client_test.go
client/config.go
client/config_test.go
cmd/rport/main.go

Refactor client config:
- move all config parsing to `config.ParseAndValidate` from `NewClient`
- add config as direct attribute of `Client`
- `NewClient` does not return error
- add tests
There shouldn't be any changes in functionality in this pr.

DEV-1763: Refactor client config

---

README.md
docs/client-on-other-os.md
server/client_listener.go
server/clients/client.go
server/clients/client_builder.go

- Use `UUID4` for client ID instead of SSH connection ID;
- Fix README

DEV-1988: Use uuid4 for client IDs, Fix README

---

cmd/rportd/main.go
rportd.example.conf
server/api_listener.go
server/bearer_auth.go
server/client_listener.go

- update logging msg when client is forced to wait on bad login
- set defaults for banning clients and api users
- return 429 for empty string username when no auth method is provided
- use info log level as default

DEV-2088-2090: Improvements

---

client/command.go
client/command_test.go
share/models/job.go

Capture everything between `<summary>` and `</summary>`. Make it part of the job result.

DEV-2455: Add job summary output sent back from client

---

server/api.go
server/upload.go

Currently whole schedule execution failed if one of the clients was disconnected. This allows disconnected clients when listing clients for schedule execution and saves appropriate error for jobs on disconnected clients later.

[DEV-2455] Allow disconnected clients when starting schedule execution

---

api-doc/openapi/components/schemas/JobPartial.yaml
server/client_listener.go

Client Id and name are needed by rportcli for correct output.

Add client id and client name to partial script outputs

---

client/updates/yum.go

These changes allow rport to successfully list and detail updates available on CentOS.
Tested on CentOS 7, testing on later CentOS/Rocky/Alma as well as RHEL is advised.
Notes from comments:
Security updates will always be 0 on CentOS-like Redhat without EPEL, as core CentOS doesn't include security metadata
"needs-restarting" requires the yum-utils package

Fixes for update checks on CentOS-like Redhat OS using yum

---

db/sqlite/sqlite.go
db/sqlite/sqlite_test.go
server/api/jobs/jobs.go
server/monitoring/sqlite.go

This PR adds explicit retry attempts when sqlite returns busy db errors (aka locked database errors). 
Other options considered were to use busy timeouts or restrict max open connections to 1. Using busy timeouts resulted in more busy errors (surprisingly) and limiting the max open connections lowered performance of writes to approx 1/2 the previous performance (not surprisingly).
https://tracker.rport.io/issue/DEV-2700/Too-many-db-locks

[DEV-2700] Too many db locks

---

client/client.go
client/config.go
client/updates/updates.go
cmd/rport/main.go
server/api_clientauth_test.go
server/api_handler_clients.go
server/api_handler_clients_test.go
server/api_handler_commands_test.go
server/api_handler_monitoring_test.go
server/api_handler_tunnels.go
server/api_listener.go
server/api_responses.go
server/client_listener.go
server/client_service.go
server/client_service_test.go
server/client_status_check.go
server/clients/client.go
server/clients/cr.go
server/clients/init.go
server/server.go
server/upload_test.go
share/logger/logger.go
share/logger/logger_test.go

This PR improves aspects of our general logging approach. We have a customer who's having problems with disconnected clients and connected tunnels being out of sync. It is proving difficult to diagnose as our logs are missing certain information about client disconnects / connects. This PR adds some of the missing info.
The PR also contains a change that isn't specifically related to improved logging that might assist with the customer problem where we will attempt to start tunnels even if the client is marked as disconnected. Ideally this would be a separate PR but in the interests of deploying a change quickly, it has been included with PR.
Also, there is a change, that will be enhanced further after the next pre-release, to log api error responses on the server side. We currently have …

[DEV-2709] Improve logging

---

server/clients/client_service.go

Reverts two locking changes in the client services that were misplaced and caused deadlocks.

[DEV-2725] Remove unnecessary locks causing deadlock

---

client/command.go
client/config.go
client/config_test.go
client/system/encoding.go
client/system/encoding_nix.go
client/system/encoding_win.go
client/system/script.go
cmd/rport/main.go
rport.example.conf
share/clientconfig/client_config.go

https://tracker.rport.io/issue/DEV-2687/broken-support-for-special-characters-on-windows

[DEV-2687] Add input and output encoding config options for interpreter aliases

---

cmd/rportd/main.go
server/caddy/config.go
server/chconfig/config.go

https://tracker.rport.io/issue/DEV-2750/unexpected-server-shut-down-on-macOS

[DEV-2750] Unexpected server shutdown on mac os

---

server/auditlog/entry.go
server/auditlog/entry_test.go

https://tracker.rport.io/issue/DEV-2749/Wrong-data-on-auditlog-response

[DEV-2749] Wrong data on auditlog response

---

client/client.go

https://tracker.rport.io/issue/DEV-2760/Tunnel-destination-is-not-allowed-by-client-configuration-after-ONE-Tunnel-Works

[DEV-2760] Add log on client when tunnel is not allowed

---

bdd/client_labels/e2e_test.go
bdd/helpers/cleanup.go
bdd/simple_client_connects/e2e_test.go

Because tests fail if there are some leftovers after previous runs
(most likely in the db)

DEV-2814 cleanup files before running tests

---

server/api/session/cache.go
server/api/session/cache_test.go
server/api/session/session.go
server/api/session/sqlite.go
server/api/session/sqlite_test.go
server/api_handler_users_test.go
server/api_middleware.go
server/bearer/bearer_auth.go

https://tracker.rport.io/issue/DEV-2843/Remove-api-session-related-data-races
This implementation uses struct copies rather than mutexes. What do we think about this?

[DEV-2843] Remove api session related data races
